import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import ConvexServerProvider from "./ConvexServerProvider";
import Header from "@/components/custom/Header";

export const metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexServerProvider>
          <Provider attribute="class" defaultTheme="dark" enableSystem>
            <Header/>
            {children}
          </Provider>
        </ConvexServerProvider>
      </body>
    </html>
  );
}
